version: '2'
services:
    portal_web-app:
        image: portal_web
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://portal_web-mysql:3306/portal_web?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    portal_web-mysql:
        extends:
            file: mysql.yml
            service: portal_web-mysql
